#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root, sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCgQ3LlmjRqRUJ65iRJLG9lEVKQ5FCS2ZPMW0Rh6Vy0PM4dpdO1mXyUns/1VXIOnDELZi8QFzPjyH04/ffOfgL/J0M09K3DL47V4g6dxGyJi/4xE0d7gcYIYpPTKc1mz/lf8/+ZDCOpN6gvLtucbC5p+5ModRaeGvh8Hu+TxI5W1+ErRrh4Uo7+3zA0UMtat9EpYt9rT9vimngkDLf49Y/2mcOLj2xM3xRKZ3eh5N2OnzKz8PqO9LfhD3YyxECsvgl9U02Tn7/0jEKJWPW0EItHqAPHMYQ8TkRjzbHB4kl9MW2X4XA5Yw8Xje2quNSnBoYYUaFT4hTE91l0Y2UI9BysggYuRP5eH7AS3MRYoX2G0wQcXiYrQOnDAUthkj4KPvWlY9JZZb+yuvgh3a5B33K57mPr+LBn69RaJjsk2WXSYVSLb60Q3y6t5fjSIuSiyIabqq7jp9fs/msPNbYPN+lh8/u1DuWmpeknqc7NcPObSZn56OsgL075tr7fXvaciM= your_email@example.com

# Clone repo and start hashicups backend
runcmd:
  - sudo su terraform
  - cd /home/terraform
  - sudo apt-get update
  - sudo apt-get -y -qq install docker.io docker-compose git
  - git clone https://github.com/hashicorp-demoapp/hashicups-setups
  - cd hashicups-setups/docker-compose-backend-deployment
  - sudo docker-compose up -d
